const countryNames: Record<string, string> = {
  NO: 'Norge',
  SE: 'Sverige',
  DK: 'Danmark',
  FI: 'Finland',
  IS: 'Island',
  DE: 'Tyskland',
  AT: 'Østerrike',
  CH: 'Sveits',
  NL: 'Nederland',
  BE: 'Belgia',
  LU: 'Luxembourg',
  FR: 'Frankrike',
  ES: 'Spania',
  PT: 'Portugal',
  IT: 'Italia',
  GB: 'Storbritannia',
  IE: 'Irland',
  PL: 'Polen',
  CZ: 'Tsjekkia',
  SK: 'Slovakia',
  HU: 'Ungarn',
  RO: 'Romania',
  BG: 'Bulgaria',
  HR: 'Kroatia',
  SI: 'Slovenia',
  EE: 'Estland',
  LV: 'Latvia',
  LT: 'Litauen',
  GR: 'Hellas',
  CY: 'Kypros',
  MT: 'Malta',
  US: 'USA',
  CA: 'Canada',
  AU: 'Australia',
  NZ: 'New Zealand',
  JP: 'Japan',
  KR: 'Sør-Korea',
  CN: 'Kina',
  IN: 'India',
  BR: 'Brasil',
  MX: 'Mexico',
  AE: 'De forente arabiske emirater',
  SA: 'Saudi-Arabia',
  IL: 'Israel',
  TR: 'Tyrkia',
  ZA: 'Sør-Afrika',
};

/** Convert country code to full Norwegian name */
export function countryName(code: string | null): string {
  if (!code) return '—';
  return countryNames[code.toUpperCase()] ?? code;
}
